services:
  - type: web
    name: Bill-Generator
    runtime: docker
    buildContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000